language: python
os:
  - linux
  - osx
matrix:
  allow_failures:
     - os: osx
python:
 - 2.7
 - 3.3
 - 3.4
 - 3.5
 - 3.6

script:
 - pip install -r dev-requirements.txt
 - python setup.py test
 - python -m flake8 malpy
 - python -m pylint malpy

install:
  python setup.py install

after_success:
  - bash <(curl -s https://codecov.io/bash)
